# last update: 2021-10-02

service: jp-feed
useDotenv: true

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-plugin-monorepo
  - serverless-add-api-key
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-2

  environment:
    TABLENAME: ${self:custom.stage}-js
    REGION: ${self:provider.region}
    INVERTINDEX: InvertedIndex
    MODELINDEX: ModelIndex
    GSI1INDEX: GSI1Index

  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

custom:
  webpack:
    webpackConfig: ../../webpack.config.js
    includeModules: true
    packager: 'yarn'
    packagerOptions:
      noFrozenLockFile: true
    forceExclude:
      - aws-sdk

  apiKeys:
    dev:
      - name: testKey

  MYSQL_DATABASE:
    dev: Dev

  stage: ${opt:stage, self:provider.stage}

functions:
  temp:
    handler: src/getFollowingFeed.handler
    events:
      - http:
          path: '/feed'
          method: get
          cors: true
          private: true
